// Codebase Atlas DATA — andysolomon/arc-worlds@main (Little Worlds)
// All file counts and KB figures come from the repo tree scan (2026-08-19).
window.ATLAS_DATA = {
  repo: 'arc-worlds · main', product: 'LITTLE WORLDS',
  stats: [
    ['TABS', '4'],
    ['WORLD TYPES', '8'],
    ['MOONS MODELLED', '22'],
    ['SOURCE', '~120 files · ~807 KB'],
    ['TEST FILES', '21'],
    ['ENGINES', '2 — v2 behind a worker'],
  ],
  overviewTitle: 'Sculpt a planet, then see who lives there',
  overviewKicker: 'LITTLE WORLDS',
  overviewSub: 'a browser planet sculptor and star-system builder',
  OVERVIEW_WHAT: [
    'This repository is a browser app for [[sculpting planets]]. A seed and about twenty sliders make a world: terrain, seas, clouds, rings, up to three moons. A spectrometer reads the atmosphere your sliders imply. The eight real planets — and Pluto, and 22 real moons — are rendered from measured data. Worlds can be arranged into star systems that orbit on real Kepler-solved paths.',
    'The core bargain: [[a world is just its params]] — under 1KB of JSON. That object is what gets saved, shared and re-rendered. There are no thumbnails anywhere; a shared /w/:slug link regenerates the world in full 3D against the engine as it exists today.',
    'The map reads top to bottom the way a request does: the React panels up top edit params, the engine in the middle turns params into pixels, the v2 terrain worker below does the heavy math off the main thread, and the small server strip files worlds into Postgres.',
  ],
  OVERVIEW_HOW: [
    'React 19 + three.js r185, bundled by Vite, run with Bun. The server is five small Vercel Functions over Neon Postgres via Drizzle — the entire backend is [[~12 KB of TypeScript]].',
    'The engine ([[src/engine]]) has no knowledge of React. PlanetViewport owns its canvas and animation loop; React creates it once and feeds it params imperatively. One function — surface.ts — decides what a world looks like in both the sculptor and the orbit view, pinned by golden samples captured before it was extracted.',
    'Terrain v2 runs in a module worker: a canonical graph/model cache stays worker-side and only finished render artifacts cross the thread boundary. Performance is an acceptance criterion — budgets live in performance-budget.json and CI rejects >10% regressions.',
  ],
  HOW_TO_READ: 'Hover anything for a plain description; click it for the full card. [[Go inside]] a structure to see its parts. TRACE walks one slider-drag end to end, from panel to Postgres.',
  GROUPS: [
    ['THE APP', ['ap','sc','sy','sn','wg']],
    ['THE ENGINE', ['ve','su','sh','sk','bk','no','pl','ty']],
    ['TERRAIN V2', ['wk','v2']],
    ['THE DOMAIN', ['pa','sl','sp','da','ow','ac']],
    ['THE SERVER', ['fn','db']],
    ['QUALITY', ['ut','e2','pf','ci']],
    ['LEGACY', ['pr']],
  ],
  STRUCTURES: [
    {id:'ap', code:'AP', name:'App shell', group:'THE APP', loc:'7 files · 55 KB', gx:2, gy:0, w:2, d:2, h:1.7,
     what:'The frame around everything: four tabs (Sculpt, Scan, Systems, Worlds), the URL routing that makes /w/:slug and /s/:slug links open a shared world or system, and the shared UI kit.',
     how:'src/App.tsx plus main.tsx, Viewport.tsx (the canvas mount), ui.tsx, display.ts and styles.css. React re-renders never rebuild the 3D scene — the viewport is created once and fed imperatively.',
     src:['src/App.tsx','src/main.tsx','src/components/Viewport.tsx','src/components/ui.tsx','src/lib/display.ts','src/styles.css','index.html'], talks:['ac','sc']},
    {id:'sc', code:'SC', name:'Sculpt panel', group:'THE APP', loc:'1 file · 17 KB', gx:5, gy:0, w:2, d:2, h:1.1,
     what:'The world-builder. Sliders for mountains, seas, clouds, ice, glow, spin; fully procedural rings and moons; eight world types; Surprise-me; ancient-world reconstructions.',
     how:'src/components/SculptPanel.tsx. Every control edits one field of PlanetParams — the panel never touches the renderer directly.', src:['src/components/SculptPanel.tsx'], talks:['pa']},
    {id:'sy', code:'SY', name:'Systems panel', group:'THE APP', loc:'1 file · 26 KB', gx:8, gy:0, w:2, d:2, h:1.4,
     what:'A star and the worlds orbiting it, in two views: a body list and a live orbit view. Holds the Solar System, four observed exoplanet systems, invented and homage systems, and yours.',
     how:'src/components/SystemsPanel.tsx. Editing goes through lib/systems.ts; the panel owns which-system-is-which rules (read-only vs editable copies).', src:['src/components/SystemsPanel.tsx'], talks:['sl']},
    {id:'sn', code:'SN', name:'Scan panel', group:'THE APP', loc:'1 file · 6 KB', gx:10.8, gy:0, w:1.5, d:1.5, h:0.6,
     what:'The spectrometer readout for whatever world is on screen: atmosphere composition, surface mineralogy, water state, biosignature assessment.',
     how:'src/components/ScanPanel.tsx — a thin view over lib/scan.ts.', src:['src/components/ScanPanel.tsx'], talks:['sp']},
    {id:'wg', code:'WG', name:'Worlds gallery', group:'THE APP', loc:'1 file · 6 KB', gx:13.1, gy:0, w:1.5, d:1.5, h:0.6,
     what:'Recently saved worlds, each with a permanent /w/:slug link. Opening one regenerates it in full 3D from stored params.',
     how:'src/components/WorldsPanel.tsx, listing through the API client with this browser\u2019s owner key.', src:['src/components/WorldsPanel.tsx'], talks:['ac']},

    {id:'pa', code:'PA', name:'Params', group:'THE DOMAIN', loc:'1 file · 9 KB', gx:1, gy:3.5, w:1.5, d:1.5, h:0.7,
     what:'The definition of a world: defaults, validation, and sanitize() — every value clamped into range. The same function runs in the browser and on the server.',
     how:'src/lib/params.ts. A hand-crafted payload cannot push an out-of-range value or asset path into anyone\u2019s renderer, because the server re-sanitizes with this exact code.', src:['src/lib/params.ts'], talks:['ve']},
    {id:'sl', code:'SL', name:'Systems lib', group:'THE DOMAIN', loc:'1 file · 23 KB', gx:3.5, gy:3.5, w:2, d:2, h:1.3,
     what:'What a star system is: bodies, orbits, moons-of-planets rules, generation from a seed, duplication, and sanitizeSystem() — which re-derives every orbital period from distance and star mass.',
     how:'src/lib/systems.ts. Kepler\u2019s third law (P² = a³/M★) sets every year; a payload cannot claim invented numbers are measured ones.', src:['src/lib/systems.ts'], talks:['ve']},
    {id:'sp', code:'SP', name:'Scan lib', group:'THE DOMAIN', loc:'1 file · 18 KB', gx:7, gy:3.5, w:1.5, d:1.5, h:1.0,
     what:'Turns params into chemistry: composition by volume, per-gas explanations, absorption lines, biosignature logic. Push sea level up on a Meadow world and the readout flags a nitrogen–oxygen atmosphere out of equilibrium.',
     how:'src/lib/scan.ts, reading the spectrometer datasets and measured profiles from src/data.', src:['src/lib/scan.ts'], talks:[]},
    {id:'ow', code:'OW', name:'Owner identity', group:'THE DOMAIN', loc:'1 file · 2 KB', gx:12, gy:3.5, w:1, d:1, h:0.35,
     what:'A self-issued anonymous key that scopes the gallery to this browser. No accounts, nothing stored about you.',
     how:'src/lib/owner.ts — an opaque key sent as a request header, never echoed back.', src:['src/lib/owner.ts'], talks:['ac']},
    {id:'ac', code:'AC', name:'API client', group:'THE DOMAIN', loc:'1 file · 3 KB', gx:10, gy:3.7, w:1, d:1, h:0.4,
     what:'listWorlds / saveWorld / getSystem — the browser\u2019s side of saving and sharing.',
     how:'src/lib/api.ts. Lists carry the owner key; per-slug reads deliberately don\u2019t, so shared links stay cacheable for everyone.', src:['src/lib/api.ts'], talks:['fn']},

    {id:'pl', code:'PL', name:'Planets (measured)', group:'THE ENGINE', loc:'1 file · 8 KB', gx:0, gy:6.5, w:1.5, d:1.5, h:0.65,
     what:'Measured values for the real bodies: axial tilt, oblateness, rotation, full orbital elements, 22 moons at real radii and periods, ring structure.',
     how:'src/engine/planets.ts. Positions are Kepler-solved, so the speed-up near perihelion is real.', src:['src/engine/planets.ts'], talks:['ve']},
    {id:'ty', code:'TY', name:'Types', group:'THE ENGINE', loc:'1 file · 11 KB', gx:2.8, gy:6.8, w:1.5, d:1.5, h:0.8,
     what:'PlanetParams and SystemDef — the whole description of a world and of a system. Everything else in the repo is a function of these two shapes.',
     how:'src/engine/types.ts. A world knows nothing about where it is: orbital facts live on the system\u2019s body, which is what lets any world drop into any system unchanged.', src:['src/engine/types.ts'], talks:[]},
    {id:'ve', code:'VE', name:'Viewport engine', group:'THE ENGINE', loc:'1 file · 139 KB', gx:5.2, gy:6.5, w:3, d:3, h:3.0,
     what:'The heart of the repo and its single biggest file. PlanetViewport owns the scene, the GPU resources and the animation loop: planet meshes, water/cloud/sky shells, the orbit view, transitions, moving fluids, and the shared clock that pauses everything together.',
     how:'src/engine/viewport.ts, three.js r185. It diffs a system in two layers — appearance and orbits — so changing a distance moves a planet without re-baking any textures. Rendering stops when paused, hidden, or scrolled offscreen.',
     src:['src/engine/viewport.ts'],
     talks:['wk'],
     children:[
       {code:'v1', name:'Scene & loop', h:0.8, what:'Canvas, renderer, camera, and the one animation loop everything rides.'},
       {code:'v2', name:'Planet mesh & shells', h:1.0, what:'Displaced terrain sphere plus water, cloud and atmosphere shells for the detailed tier.'},
       {code:'v3', name:'Orbit view', h:0.9, what:'Everything orbiting its star on elliptical, inclined, Kepler-solved paths.'},
       {code:'v4', name:'Fluids clock', h:0.6, what:'Water shimmer, creeping lava, drifting gas bands — all on the rotation clock, so pausing freezes every fluid.'},
       {code:'v5', name:'Moon frames', h:0.6, what:'Stand on a moon and its planet wheels overhead at its true angular size — Jupiter fills 12° of Europa\u2019s sky.'},
       {code:'v6', name:'Transitions', h:0.5, what:'The sculptor-to-orbit transition, budgeted and benchmarked: ≤4 shader programs added.'}]},
    {id:'su', code:'SU', name:'Surface & climate', group:'THE ENGINE', loc:'4 files · 29 KB', gx:9.2, gy:6.5, w:2, d:2, h:1.2,
     what:'What a world looks like, as a function of direction. The ONE place that decides a sculpted world\u2019s appearance — both views share it, so the same seed can never read as two different planets.',
     how:'src/engine/surface.ts + heightfield.ts + climate.ts + palettes.ts. golden samples captured before extraction prove the refactor invisible to saved worlds.',
     src:['src/engine/surface.ts','src/engine/heightfield.ts','src/engine/climate.ts','src/engine/palettes.ts'], talks:['ve','bk']},
    {id:'sk', code:'SK', name:'Sky', group:'THE ENGINE', loc:'1 file · 6 KB', gx:12.4, gy:6.5, w:1, d:1, h:0.5,
     what:'Star field, exposure and the nebula wash — a per-browser viewer preference, never part of a world or a shared link.',
     how:'src/engine/sky.ts; the nebula is plain CSS behind the transparent canvas, so it costs the GPU nothing.', src:['src/engine/sky.ts'], talks:['ve']},
    {id:'no', code:'NO', name:'Noise & scale', group:'THE ENGINE', loc:'2 files · 13 KB', gx:2.8, gy:9.3, w:1.5, d:1.5, h:0.75,
     what:'Seeded PRNG, 3D simplex noise and fbm; scale models, Kepler solving, orbital periods. The math everything procedural stands on.',
     how:'src/engine/noise.ts + scale.ts. The same Kepler law reproduces all nine measured periods to the nearest year — which is what makes it fair for invented worlds.', src:['src/engine/noise.ts','src/engine/scale.ts'], talks:['su']},
    {id:'sh', code:'SH', name:'Shaders & materials', group:'THE ENGINE', loc:'2 files · 13 KB', gx:9.5, gy:9.5, w:1.5, d:1.5, h:0.75,
     what:'GLSL for rings, gas giants, stars and atmospheres — Saturn\u2019s Cassini division, Neptune\u2019s clumpy arcs, star granulation rebuilt per colour, all generated rather than textured.',
     how:'src/engine/shaders.ts + materials.ts. Rings cast a shadow onto the planet; the unlit face renders dimmer.', src:['src/engine/shaders.ts','src/engine/materials.ts'], talks:['ve']},
    {id:'bk', code:'BK', name:'Bake pipeline', group:'THE ENGINE', loc:'3 files · 8 KB', gx:12.2, gy:8.6, w:1, d:1, h:0.5,
     what:'The surface rendered to a small map, for orbit-view planets — at a few dozen pixels across a planet needs no displaced geometry.',
     how:'src/engine/bake.ts + bake.worker.ts + v1-artifacts.ts, in a worker.', src:['src/engine/bake.ts','src/engine/bake.worker.ts','src/engine/v1-artifacts.ts'], talks:['ve']},

    {id:'wk', code:'WK', name:'Worker bridge', group:'TERRAIN V2', loc:'4 files · 27 KB', gx:5.5, gy:10.6, w:1.5, d:1.5, h:0.95,
     what:'The main thread\u2019s handle on the v2 terrain worker: a typed wire protocol, latest-wins job slots, cancel/suspend, and a strict rule that only finished render artifacts cross the thread boundary.',
     how:'src/engine/v2/client.ts + worker.ts + protocol.ts + terrain.worker.ts. Canonical model buffers never leave the worker\u2019s 12-model cache.',
     src:['src/engine/v2/client.ts','src/engine/v2/worker.ts','src/engine/v2/protocol.ts','src/engine/v2/terrain.worker.ts'], talks:['v2']},
    {id:'v2', code:'V2', name:'Terrain v2', group:'TERRAIN V2', loc:'5 files · 92 KB', gx:7.8, gy:11.4, w:2.5, d:2.5, h:2.2,
     what:'The new terrain generator: a canonical graph grown per world, a model computed over it, then flat maps or displaced-mesh buffers baked from the model — plus ecosystems and clouds.',
     how:'src/engine/v2/ — model.ts (42 KB) is the largest module after the viewport. Runs entirely in the worker; heavy buffers are transferred, never copied.',
     src:['src/engine/v2/model.ts','src/engine/v2/artifacts.ts','src/engine/v2/graph.ts','src/engine/v2/ecosystems.ts','src/engine/v2/clouds.ts'],
     talks:[],
     children:[
       {code:'g', name:'graph.ts', h:0.6, what:'The canonical terrain graph a world\u2019s seed grows — fixed bytes, cached worker-side.'},
       {code:'m', name:'model.ts', h:1.2, what:'The terrain model computed over the graph: elevation, moisture, temperature. 42 KB — the big one.'},
       {code:'a', name:'artifacts.ts', h:0.9, what:'Bakes the model into what the renderer actually consumes: flat RGBA maps or positions/colors/normals buffers.'},
       {code:'e', name:'ecosystems.ts', h:0.4, what:'Who lives where, from climate bands.'},
       {code:'c', name:'clouds.ts', h:0.4, what:'Cloud fields over the terrain model.'}]},

    {id:'da', code:'DA', name:'Data & presets', group:'THE DOMAIN', loc:'6 files · 84 KB', gx:0, gy:9.6, w:2, d:2, h:1.7,
     what:'Everything the app knows by heart: the eight world types, measured planet and moon profiles, ancient-Earth and fiction reconstructions, the spectrometer datasets, and the built-in star systems.',
     how:'src/data/ — hand-written measured profiles are what let Pluto and seven moons scan as themselves.',
     src:['src/data/presets.ts','src/data/profiles.ts','src/data/moon-profiles.ts','src/data/fiction.ts','src/data/spectrometer.ts','src/data/systems.ts'],
     talks:['sl','sp','pa'],
     children:[
       {code:'p', name:'presets.ts', h:0.5, what:'The eight world types plus ancient and fiction presets, each with a canonical seed.'},
       {code:'pr', name:'profiles.ts', h:0.9, what:'Measured planet profiles — 27 KB of real numbers.'},
       {code:'mp', name:'moon-profiles.ts', h:0.7, what:'Hand-written measured profiles for the seven visitable moons.'},
       {code:'f', name:'fiction.ts', h:0.4, what:'Homage worlds: Erid, Adrian, Polyphemus, Pandora — labelled invented everywhere.'},
       {code:'sm', name:'spectrometer.ts', h:0.5, what:'Gas lines, minerals, and the explanations the Scan tab prints.'},
       {code:'sy', name:'systems.ts', h:0.5, what:'The Solar System, TRAPPIST-1, Proxima, 51 Peg, Kepler-452, Andromeda.'}]},

    {id:'fn', code:'FN', name:'API functions', group:'THE SERVER', loc:'5 files · 12 KB', gx:12, gy:11.6, w:1.5, d:1.5, h:0.75,
     what:'The entire backend: list/save/fetch for worlds and systems. Mints an 8-char slug (no vowels, so no accidental words) and an edit token returned only to the creator.',
     how:'api/ — Vercel Functions. Incoming params are re-sanitized with the same functions the UI uses; gallery lists are private/no-store so a CDN can never hand out someone else\u2019s gallery.',
     src:['api/worlds/index.ts','api/worlds/[slug].ts','api/systems/index.ts','api/systems/[slug].ts','api/_lib.ts'],
     talks:['db'],
     children:[
       {code:'w', name:'worlds/index.ts', h:0.5, what:'GET your gallery, POST a new world.'},
       {code:'ws', name:'worlds/[slug].ts', h:0.3, what:'One world by slug — immutable, cached for a year.'},
       {code:'s', name:'systems/index.ts', h:0.4, what:'GET your systems, POST a new one.'},
       {code:'ss', name:'systems/[slug].ts', h:0.3, what:'One system by slug.'},
       {code:'l', name:'_lib.ts', h:0.3, what:'Slug + token minting, name cleaning, owner-key reading, cache policy.'}]},
    {id:'db', code:'DB', name:'Database', group:'THE SERVER', loc:'2 files · 4 KB', gx:14.3, gy:12.9, w:2, d:1.3, h:0.3, slab:1,
     what:'Two tables: worlds and systems. Each row\u2019s params/def column IS the artifact — no images stored, ever.',
     how:'db/schema.ts (Drizzle) + a lazy Neon serverless client. Indexed by owner + created-at, because the gallery only ever reads one owner\u2019s newest rows.', src:['db/schema.ts','db/index.ts'], talks:[]},

    {id:'ut', code:'UT', name:'Unit tests', group:'QUALITY', loc:'19 files · ~129 KB', gx:0.5, gy:12.9, w:2, d:1.3, h:0.3, slab:1,
     what:'Vitest across engine, v2, lib and data — including golden surface samples and golden artifacts that pin rendering behaviour through refactors.',
     how:'*.test.ts + goldens. systems.test.ts alone is 26 KB — the orbital rules are the most-tested code in the repo.', src:['src/engine/*.test.ts','src/engine/v2/*.test.ts','src/lib/*.test.ts'], talks:[]},
    {id:'e2', code:'E2', name:'E2E & visual', group:'QUALITY', loc:'2 files · 56 KB', gx:0, gy:15, w:2, d:1.3, h:0.3, slab:1,
     what:'Playwright against a real production build, plus visual snapshot specs for the renderer.',
     how:'e2e/app.spec.ts (49 KB) + e2e/visual/render.spec.ts.', src:['e2e/app.spec.ts','e2e/visual/render.spec.ts'], talks:[]},
    {id:'pf', code:'PF', name:'Perf harness', group:'QUALITY', loc:'3 files · 26 KB', gx:3.2, gy:14.2, w:1.5, d:1.5, h:0.8,
     what:'Performance is an acceptance criterion here: bundle-size gates, browser benchmarks of the orbit transition, terrain benchmarks, and per-metric noise floors so shared CI runners don\u2019t cry wolf.',
     how:'src/perf/ + performance-budget.json. The orbit transition may add at most four shader programs.', src:['src/perf/v2-terrain-benchmark.ts','src/perf/v2-terrain-gates.ts','performance-budget.json'], talks:[]},
    {id:'ci', code:'CI', name:'CI workflows', group:'QUALITY', loc:'2 files · 4 KB', gx:5.9, gy:15.2, w:1, d:1, h:0.45,
     what:'Typecheck, lint, unit, e2e on every PR; a performance workflow that benchmarks the PR against its own base revision and rejects regressions over 10%.',
     how:'.github/workflows/ci.yml + performance.yml, on GitHub Actions.', src:['.github/workflows/ci.yml','.github/workflows/performance.yml'], talks:[]},

    {id:'pr', code:'PR', name:'Prototype', group:'LEGACY', loc:'3 files · 200 KB', gx:11.5, gy:15.4, w:2, d:1.6, h:0.3, slab:1,
     what:'The original single-file prototype, still runnable, unchanged. Deliberately connected to nothing — it is the fossil record the app grew from.',
     how:'prototype/Little Worlds.dc.html + planet-engine.js, loading three.js 0.152 and React 18 from CDN.', src:['prototype/Little Worlds.dc.html','prototype/planet-engine.js'], talks:[]},
  ],
  EDGES: [
    {f:'sc', t:'pa', flow:1, pay:'slider values'},
    {f:'pa', t:'ve', flow:1, pay:'clean PlanetParams'},
    {f:'ve', t:'wk', flow:1, pay:'render request ⇄ buffers'},
    {f:'wk', t:'v2', flow:1, pay:'terrain job'},
    {f:'sy', t:'sl', pay:'system edits'},
    {f:'sl', t:'ve', pay:'SystemDef'},
    {f:'da', t:'sl', pay:'built-in systems'},
    {f:'da', t:'pa', pay:'presets'},
    {f:'da', t:'sp', pay:'spectrometer datasets'},
    {f:'sn', t:'sp', pay:'current params'},
    {f:'pl', t:'ve', pay:'measured planets', via:[[1.2,8.2]]},
    {f:'no', t:'su', pay:'noise fields', via:[[6.8,10.2]]},
    {f:'su', t:'ve', pay:'vertex colors'},
    {f:'su', t:'bk', pay:'texel colors'},
    {f:'bk', t:'ve', pay:'baked maps'},
    {f:'sh', t:'ve', pay:'GLSL programs'},
    {f:'sk', t:'ve', pay:'sky shells', via:[[12.9,5.8]]},
    {f:'ty', t:'ve', dashed:1, pay:'type contracts'},
    {f:'ap', t:'ac', flow:1, pay:'save & open'},
    {f:'wg', t:'ac', pay:'list & open', via:[[13.8,4.2]]},
    {f:'ow', t:'ac', pay:'owner key'},
    {f:'ac', t:'fn', flow:1, pay:'params as JSON, over HTTPS', via:[[13.5,4.5]]},
    {f:'fn', t:'pa', dashed:1, pay:'same sanitize()', via:[[12.7,5]]},
    {f:'fn', t:'db', flow:1, pay:'rows'},
    {f:'ci', t:'ut', dashed:1, pay:'every PR'},
    {f:'ci', t:'e2', dashed:1, pay:'every PR'},
    {f:'ci', t:'pf', dashed:1, pay:'base-vs-PR benchmark'},
  ],
  EXTERNALS: [
    {name:'NEON POSTGRES', t:'db', dx:3.2, dy:1.2},
    {name:'VERCEL EDGE', t:'fn', dx:3.4, dy:-0.6},
    {name:'THREE.JS r185 · REACT 19', t:'ve', dx:4.2, dy:-2.4},
    {name:'CC-BY PLANET TEXTURES', t:'pl', dx:-2.6, dy:-1.4},
    {name:'GITHUB ACTIONS', t:'ci', dx:-1.6, dy:1.8},
  ],
  TRACE: [
    ['ap','You open the app. App.tsx reads the URL — a /w/:slug link means someone shared a world; otherwise you land on the Sculpt tab.'],
    ['sc','You drag a slider. SculptPanel edits one field of PlanetParams — the seed plus ~20 numbers that ARE the world.'],
    ['pa','params.ts sanitizes: every value clamped into range. The same function will run again on the server later.'],
    ['ve','viewport.ts diffs old params against new. Only what actually changed invalidates — a presentation edit never triggers a rebake.'],
    ['wk','The heavy terrain math leaves the main thread: the worker bridge posts a render job, latest-wins per consumer slot.'],
    ['v2','In the worker, graph.ts grows the canonical terrain graph, model.ts computes elevation and climate over it, artifacts.ts bakes the buffers. The canonical model stays cached worker-side.'],
    ['su','surface.ts colors the world — the one function both the sculptor and the orbit view share, so a seed always looks like itself.'],
    ['ve','Buffers transfer back and three.js draws the sphere, water, clouds and sky. The fluids ride the rotation clock: pause the world and everything freezes with it.'],
    ['sp','Meanwhile scan.ts reads the same params and writes the spectrometer story: what this atmosphere is made of and which absorption lines would give it away.'],
    ['ac','You hit Save. api.ts POSTs the name and params — under 1KB of JSON — with this browser\u2019s anonymous owner key.'],
    ['fn','api/worlds re-sanitizes server-side, mints an 8-char slug and an edit token returned only to you.'],
    ['db','Drizzle inserts the row into Neon Postgres. The params column IS the world; no image is stored.'],
    ['ap','A friend opens /w/:slug. The params come back and the engine regenerates the world in full 3D — as it exists against today\u2019s renderer, not a stale picture.'],
  ],
};
